[platformio]
default_envs = painter
boards_dir = boards

[env]
platform = espressif32@6.12.0
board = T5-ePaper-S3
framework = arduino
monitor_speed = 115200
upload_speed = 460800
build_unflags = -std=gnu++11
build_flags =
    -std=gnu++17
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_LOOP_STACK_SIZE=16384
    -DLILYGO_T5_EPD47_S3

[env:painter]
build_flags =
    ${env.build_flags}
    -DLAB_PAINTER
    -DEPD_PAINTER_PRESET_AUTO
lib_deps = https://github.com/tonywestonuk/EPD_Painter.git#6335a149c5a9b3be4150880e0be64ef2529ba62a

[env:lilygo]
lib_deps = https://github.com/Xinyuan-LilyGO/LilyGo-EPD47.git#391b0e25d7a39897e3a00af34053250df031d699
