"""Build the on-device English catalog; Russian source labels remain available."""
from pathlib import Path
import json
import re

ROOT = Path(__file__).resolve().parents[1]


def generate():
    catalog = json.loads((ROOT / 'assets/locales/en.json').read_text('utf-8'))
    format_fields = re.compile(r'%(?!%)(?:[-+0 #]*\d*(?:\.\d+)?[hlz]*[diuoxXfFeEgGcs])')
    rows = []
    for russian, english in sorted(catalog.items()):
        if format_fields.findall(russian) != format_fields.findall(english):
            raise ValueError('Changed format arguments: ' + russian)
        rows.append('    {' + json.dumps(russian, ensure_ascii=False) + ',' + json.dumps(english, ensure_ascii=False) + '},')
    return ('// Generated by tools/generate_i18n.py from assets/locales/en.json.\n'
            '#pragma once\nnamespace I18n {\nstruct Translation {const char *ru; const char *en;};\n'
            'inline constexpr Translation catalog[] = {\n' + '\n'.join(rows) + '\n};\n}\n')


if __name__ == '__main__':
    (ROOT / 'include/i18n_catalog.h').write_text(generate(), encoding='utf-8')
