"""Generate the tracked EPD reader font from a local TrueType font.

The pinned LILYGO dependency includes epdiy's font converter, but its default
configuration only exports ASCII. This wrapper uses that exact converter with
the small set of Unicode ranges needed by Russian FB2 books and the reader UI.
The generated header is committed, so a normal firmware build does not depend
on the host font or FreeType.
"""

from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path


INTERVALS = """intervals = [
    (0x20, 0x7E),       # Basic Latin
    (0xA0, 0xBF),       # NBSP and Russian-style angle quotes
    (0x400, 0x45F),     # Cyrillic, including Ё/ё
    (0x2010, 0x2011),   # Hyphen and non-breaking hyphen
    (0x2013, 0x2015),   # En/em/horizontal dashes
    (0x2017, 0x201E),   # Smart quotes
    (0x2020, 0x2022),   # Dagger and bullet
    (0x2025, 0x2027),   # Two-dot leader, ellipsis and hyphenation point
    (0x20AC, 0x20AC),   # Euro
    (0x2116, 0x2116),   # Numero sign
]
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--font", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--name", default="ReaderRoboto16")
    parser.add_argument("--size", default=16, type=int)
    args = parser.parse_args()

    project_root = Path(__file__).resolve().parents[1]
    converter = (
        project_root
        / ".pio"
        / "libdeps"
        / "t5_epaper_s3_fast"
        / "LilyGo-EPD47"
        / "scripts"
        / "fontconvert.py"
    )
    if not converter.is_file():
        parser.error(
            "Pinned LILYGO font converter is missing; build firmware once first"
        )
    if not args.font.is_file():
        parser.error(f"Font file does not exist: {args.font}")

    source = converter.read_text(encoding="utf-8")
    replaced, count = re.subn(
        r"intervals = \[.*?\]\n\n",
        INTERVALS + "\n",
        source,
        count=1,
        flags=re.DOTALL,
    )
    if count != 1:
        raise RuntimeError("Could not locate the converter's interval table")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="reader-font-") as temp_dir:
        patched_converter = Path(temp_dir) / "fontconvert.py"
        patched_converter.write_text(replaced, encoding="utf-8")
        completed = subprocess.run(
            [
                sys.executable,
                str(patched_converter),
                "--compress",
                args.name,
                str(args.size),
                str(args.font),
            ],
            check=True,
            stdout=subprocess.PIPE,
            env={**os.environ, "PYTHONIOENCODING": "utf-8"},
        )

    banner = (
        "// Generated by tools/generate_reader_font.py from "
        f"{args.font.name}.\n"
        "// Covers ASCII, core Cyrillic and punctuation used by Russian FB2.\n"
    )
    generated = b"\n".join(
        line.rstrip() for line in completed.stdout.splitlines()
    ) + b"\n"
    args.output.write_bytes(banner.encode("utf-8") + generated)
    print(f"Generated {args.output} ({args.output.stat().st_size:,} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
