"""Generate redistributable UI fonts at exact pixel sizes using pinned epdiy."""
from pathlib import Path
import os
import re
import subprocess
import sys
import tempfile
import freetype

ROOT = Path(__file__).resolve().parents[1]

def main():
    converter = ROOT / '.pio/libdeps/t5_epaper_s3_fast/LilyGo-EPD47/scripts/fontconvert.py'
    original = converter.read_text(encoding='utf-8')
    output = ROOT / 'include/bookish_fonts'
    output.mkdir(exist_ok=True)
    for family, sizes in [('Lora', [25, 31, 39]), ('Arimo', [10, 18, 22])]:
        font = ROOT / f'assets/fonts/{family.lower()}/{family}[wght].ttf'
        face = freetype.Face(str(font))
        # Keep complete Latin/Cyrillic coverage available in each licensed font.
        points = [i for lo, hi in [(32, 255), (0x400, 0x45f), (0x2010, 0x2027),
                                   (0x20ac, 0x20ac), (0x2116, 0x2116)]
                  for i in range(lo, hi + 1) if face.get_char_index(i)]
        intervals = 'intervals = [' + ','.join(f'({i},{i})' for i in points) + ']\n\n'
        source = re.sub(r'intervals = \[.*?\]\n\n', intervals, original, count=1, flags=re.S)
        source = source.replace('face.set_char_size(size << 6, size << 6, 150, 150)',
                                'face.set_pixel_sizes(0, size)')
        with tempfile.TemporaryDirectory() as folder:
            script = Path(folder) / 'fontconvert.py'
            script.write_text(source, encoding='utf-8')
            for size in sizes:
                name = f'Bookish{family}{size}'
                result = subprocess.run([sys.executable, str(script), '--compress', name,
                                         str(size), str(font)], check=True, capture_output=True,
                                        env={**os.environ, 'PYTHONIOENCODING': 'utf-8'})
                (output / f'{name}.h').write_bytes(
                    b'// Generated by tools/generate_bookish_fonts.py; font license: assets/fonts.\n'
                    + b'\n'.join(line.rstrip() for line in result.stdout.splitlines()) + b'\n')
                print(name, len(result.stdout))

if __name__ == '__main__':
    main()
